[tool.ruff]
target-version = "py310"

select = ["F", "E", "I", "C4", "DTZ", "ISC", "ICN", "PT", "SIM"]
# Проверить правила после SIM:
# https://docs.astral.sh/ruff/rules/#flake8-simplify-sim

# Same as Black.
line-length = 88

# не проверять эти папки
exclude = [
  ".pytest_cache",
  "__pycache__",
  ".vscode",
  ".git",
  ".gitlab",
  ".venv",
]
